language: python
# Version to Test Against
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

# Install Dependencies
install:
    - pip install nose
    - pip install pyyaml
    - pip install coveralls

# Run Tests
script:
    - 'export PYTHONPATH="${PYTHONPATH}:./lib"'
    - "coverage run --source=ansibledocgen $(which nosetests) -w test/units/"

after_success:
    - coveralls
