language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
    - pip install nose
    - pip install pyyaml
    - pip install coveralls
# command to run tests
script:
    - 'export PYTHONPATH="${PYTHONPATH}:./lib"'
    - "coverage run --source=ansibledocgen $(which nosetests) -w test/units/"
after_success:
    - coveralls