language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install nose"
# command to run tests
script: 'export PYTHONPATH="${PYTHONPATH}:./lib"; nosetests -w test/units/'